### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by minhnimble** [hsu-hsu/nimble-survey-app#12]
Hello Hsu 👋 , thank you for your effort on the code submission. I am Mike, Engineering Lead at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Just so you know, you don't have to close any of my created issues after merging your PRs; I will help verify and close them for you once they pass. 😇

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by hsu-hsu** [comment]
Hello Mike,

Thank you for reviewing my code submission and I am happy to fix the issues for the improvements.

I will solve the issues as fast as I can and I will make sure to be responsive during this code review process. I will use proper git flow while solving those issues.

I really appreciate this opportunity to work with you on this project and I will try my best on fixing the issues.

Wish you have a nice day.

Best regards,
Hsu.

**Comment by minhnimble** [comment]
Hi, Hsu 👋

For your information, I just complete the 1st round of review now. Please go ahead and provide your feedback on all the proposed issues. Regarding the timeline, please note that the target is to conclude everything by the end of Thursday, thus it would be best if you could address the issues before that time. If you have any further inquiry, please don't hesitate to communicate them here.

Have a great day! ☀️

**Comment by hsu-hsu** [comment]
Hello Mike,

Thank you for reviewing my code and feedback. I will try to fix all the issues by the end of Thursday.

If I have any inquiry or concern during the process, I will reach out to you here.

I wish you to have a great day too.

Best regards,
Hsu.

**Comment by hsu-hsu** [comment]
Hello Mike,

I would like to inform you that I fixed all the issues you addressed here.

I create a new branch for each issuse and create pull request and I also explain why I solved like that in comment. You can check the latest codebase in develop branch.

If you have questions about my answesr and solutions, I am happy to discuss with you and to receive your ideas and guidance. 

I really happy working with you through this process and hope to get your feedback soon.

Wish you to have a wonderful day.

Best regards,
Hsu.

**Comment by minhnimble** [comment]
Hello Hsu, thank you for your timely update! Now, I encounter an build failed issue when getting the latest code from your submission - https://github.com/hsu-hsu/nimble-survey-app/commit/666f53bf87c5f37f3de05ef2ae9474dbde6cd935. Please double check this issue and address it so that I can verify your fixes.

![Screenshot 2023-11-16 at 18 18 19](https://github.com/hsu-hsu/nimble-survey-app/assets/70877098/487d8b04-2b5b-436b-9845-625c7b29dcb2)

At the same time, please note that no new submissions on the existing issues will be needed from your end, and the build failed fix will be the last acceptable change.

**Comment by hsu-hsu** [comment]
Hello Mike,

I check out to 666f53b and run the project and it is working fine in my laptop. I am sorry but can you please Invalid cache & Restart the android studio and make project again. 

If the error isn't gone by doing so, can you please check the project JDK in file -> Project Structure -> SDK Location -> Gradle Setting and make sure to use version 18.

If it won't solve the problem, can please kindly contact again? I will try to solve doing my best.

https://github.com/hsu-hsu/nimble-survey-app/assets/29304111/3c2b6262-2b54-4137-abbc-2e75fc35ffe9


<img width="1440" alt="Screenshot 2023-11-16 at 6 23 41 PM" src="https://github.com/hsu-hsu/nimble-survey-app/assets/29304111/22b13e43-3a3b-4e97-87e7-0a91766e4413">

**Comment by minhnimble** [comment]
Hello Hsu,

Thank you for your timely support on the build fail issue, all work properly after a clean rebuild! As of this point, my review for this code challenge session has concluded, and thus, no more submissions will be needed from you. For the next step, you will hear from the Talent Acquisition team about the decision as soon as possible. 🙏

In the end, it was a good pleasure reviewing your code and getting to know you, you have performed well. 👍 I wish you all the very best. 🍀
