### ISSUE TITLE
[Bug] Stuck at a loading state when there is no internet connection on Login page

### ISSUE THREAD

**Issue by minhnimble** [hsu-hsu/nimble-survey-app#14]
## Issue

When attempting to log in to the application without any connection, the app stucks at loading state forever.

## Expect

The application should show a proper error message stating to the user that there is not a network connection.

## Steps to reproduce

- Log in to the application without any connection:

https://github.com/hsu-hsu/nimble-survey-app/assets/70877098/efd8e464-df72-4745-82de-5311e23c3f4a

**Comment by hsu-hsu** [comment]
I add a network status interceptor to check network connectivity in this pull request.
pull request -> #23
