### ISSUE TITLE
[Bug] User can login with any combination of username/password

### ISSUE THREAD

**Issue by minhnimble** [hsu-hsu/nimble-survey-app#15]
## Issue

When the user provides any combination of email and password (including invalid credentials), the app always sends the user to the Survey List screen.

## Expect

There should be an error dialog to prevent the user to access the application. 

## Steps to reproduce

- Provide an invalid combination of email and password:

https://github.com/hsu-hsu/nimble-survey-app/assets/70877098/75e6b64a-351d-4627-9430-511553084478

**Comment by hsu-hsu** [comment]
In this pull request, I handle error response and show user with a toast. As for improvement, we can add validation in edittext. I will add this feature if I have extra time after solving other issues.
pull request -> #24
