### ISSUE TITLE
[Feature] Application flavors handling

### ISSUE THREAD

**Issue by minhnimble** [hsu-hsu/nimble-survey-app#19]
As per our API [documentation](https://github.com/nimblehq/nimble-survey-web/wiki/REST-API#ios), there are two environments that our API can support: `Staging` and `Production`. Now, you handle these environments by setting the `BASE_URL` settings in the `Constants` file for `Production` url only, and it is not the best practice for managing this kind of task.

https://github.com/hsu-hsu/nimble-survey-app/blob/81c798e104ee3a1fa125d72e060540d0ac316a86/app/src/main/java/com/nimble/android/utils/Constants.kt#L5

Thus, I would like to know more about your knowledge on this topic. Do you know any better approach to handle this? If yes, please update the project with some implementation examples. 🙂

By the way, do you have any experience handling DevOps (CI/CD) for different environments? Please brief me on the potential steps in a distribution pipeline per the environment setup.

**Comment by hsu-hsu** [comment]
Configurations build variants is very important in android and it is my fault I didn’t setup this config in previous submission. Now, I divide productFlavors into two modes(production and staging) and return base api url accordingly.
pull request -> #27

**Comment by hsu-hsu** [comment]
About handling DevOps(CI/CD), I don't have real worl experience. I only tested by myself using Codemagic and configuring a YAML file. In my opinion, if we use Codemagic, I should setup the config with production environment like below.
- Trigger the pipeline when something is pushed to the master branch.
- Setup instance_type to use.
- Run unit tests.
- Build the app (if the previous step passes).
- Publish the app to the relevant channel/environment .
- Post a message there when the build starts.
- Upload the app to Firebase App Distribution and deploy it to the QA Team.
